config/routes.rb
AptSvc::Application.routes.draw do
  resources :apartments, :except => :edit

end

app/models/apartment.rb
class Apartment < ActiveRecord::Base
  attr_accessible :address, :baths, :beds, :name, :rent
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  # GET /apartments
  # GET /apartments.json
  def index
    @apartments = Apartment.all

    render json: @apartments
  end

  # GET /apartments/1
  # GET /apartments/1.json
  def show
    @apartment = Apartment.find(params[:id])

    render json: @apartment
  end

  # GET /apartments/new
  # GET /apartments/new.json
  def new
    @apartment = Apartment.new

    render json: @apartment
  end

  # POST /apartments
  # POST /apartments.json
  def create
    @apartment = Apartment.new(params[:apartment])

    if @apartment.save
      render json: @apartment, status: :created, location: @apartment
    else
      render json: @apartment.errors, status: :unprocessable_entity
    end
  end

  # PUT /apartments/1
  # PUT /apartments/1.json
  def update
    @apartment = Apartment.find(params[:id])

    if @apartment.update_attributes(params[:apartment])
      head :no_content
    else
      render json: @apartment.errors, status: :unprocessable_entity
    end
  end

  # DELETE /apartments/1
  # DELETE /apartments/1.json
  def destroy
    @apartment = Apartment.find(params[:id])
    @apartment.destroy

    head :no_content
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/apartments/_form.html.erb
<%= form_for(@apartment) do |f| %>
  <% if @apartment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@apartment.errors.count, "error") %> prohibited this apartment from being saved:</h2>

      <ul>
      <% @apartment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :beds %><br />
    <%= f.number_field :beds %>
  </div>
  <div class="field">
    <%= f.label :baths %><br />
    <%= f.number_field :baths %>
  </div>
  <div class="field">
    <%= f.label :rent %><br />
    <%= f.number_field :rent %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/apartments/edit.html.erb
<h1>Editing apartment</h1>

<%= render 'form' %>

<%= link_to 'Show', @apartment %> |
<%= link_to 'Back', apartments_path %>

app/views/apartments/index.html.erb
<h1>Listing apartments</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Beds</th>
    <th>Baths</th>
    <th>Rent</th>
    <th>Address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @apartments.each do |apartment| %>
  <tr>
    <td><%= apartment.name %></td>
    <td><%= apartment.beds %></td>
    <td><%= apartment.baths %></td>
    <td><%= apartment.rent %></td>
    <td><%= apartment.address %></td>
    <td><%= link_to 'Show', apartment %></td>
    <td><%= link_to 'Edit', edit_apartment_path(apartment) %></td>
    <td><%= link_to 'Destroy', apartment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Apartment', new_apartment_path %>

app/views/apartments/new.html.erb
<h1>New apartment</h1>

<%= render 'form' %>

<%= link_to 'Back', apartments_path %>

app/views/apartments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @apartment.name %>
</p>

<p>
  <b>Beds:</b>
  <%= @apartment.beds %>
</p>

<p>
  <b>Baths:</b>
  <%= @apartment.baths %>
</p>

<p>
  <b>Rent:</b>
  <%= @apartment.rent %>
</p>

<p>
  <b>Address:</b>
  <%= @apartment.address %>
</p>


<%= link_to 'Edit', edit_apartment_path(@apartment) %> |
<%= link_to 'Back', apartments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AptSvc</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>